apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.express_service.name }} 
  namespace: {{ .Values.namespace }}   
spec:
  selector:
    app: {{ .Values.express.label_name }}
  ports:
    - protocol: {{ .Values.express_service.protocol }}
      port: {{ .Values.express_service.port }}
      targetPort: {{ .Values.express_service.target_port }}