apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.express.name }}    
  labels:
    app: {{ .Values.express.label_name }}
spec:
  replicas: {{ .Values.express.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.express.label_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.express.label_name }}
    spec:
      containers:
      - name: {{ .Values.express.label_name }}
        image: {{ .Values.express.image }}
        ports:
        - containerPort: {{ .Values.express.container_port }}
        env:
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.configmap.name }}
              key: {{ .Values.configmap.db_url_key }}
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secret.name }}
              key: {{ .Values.mongodb.username_key }}
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secret.name }}
              key: {{ .Values.mongodb.password_key }}
        volumeMounts:
          mountPath: {{ .Values.volume.mount_path }}
      volumes: 
        - name: {{ .Values.volume.name }}
          persistentVolumeClaim: 
            claimName: {{ .Values.pvc.name }}