apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ .Values.namespace }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
    paths:
    - backend:
        serviceName: {{ .Values.express_service.name }}
        servicePort: {{ .Values.express_service.port }}