apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongodb_service.name }}    
spec:
  selector:
    app: {{ .Values.mongodb.label }}
  ports:
    - protocol: {{ .Values.mongodb_service.protocol }}
      port: {{ .Values.mongodb_service.port }}
      targetPort: {{ .Values.mongodb_service.target_port }}