apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name }}
spec:
  storageClassName: {{ .Values.pv.storage_class }}
  accessModes:
    - {{ .Values.pv.access_mode }} 
  resources:
    requests:
      storage: {{.Values.pvc.storage}}