apiVersion: v1
kind: Secret
metadata: 
  name: {{ .Values.secret.name }}  
type: Opaque 
data:
  mongo-username: {{ .Values.secret.mongo_username }}  
  mongo-password: {{ .Values.secret.mongo_password }}